name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the Repository
      uses: actions/checkout@master
      
    - name: Build the Docker image
      run: |
        docker build ansible --file ansible/Dockerfile --tag ansible:$(date +%s)
